<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>DlbPrecision.Sensors</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DlbPrecision.Shared/DlbPrecision.Shared.csproj" />
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.6" />
  </ItemGroup>
</Project>
